export const MULTI_ADVANCED_SETTINGS_CHANGED = 'MULTI_ADVANCED_SETTINGS_CHANGED';
export const SHORT_ADVANCED_SETTINGS_CHANGED = 'SHORT_ADVANCED_SETTINGS_CHANGED';
export const SINGLE_ADVANCED_SETTINGS_CHANGED = 'SINGLE_ADVANCED_SETTINGS_CHANGED';
export const SINGLE_SELECT_ANSWERS_ADD_NEW = 'SINGLE_SELECT_ANSWERS_ADD_NEW';
export const SINGLE_SELECT_ANSWERS_REMOVE = 'SINGLE_SELECT_ANSWERS_REMOVE';
export const SINGLE_SELECT_ANSWERS_CHANGED = 'SINGLE_SELECT_ANSWERS_RADIO_CHANGED';
